export const Data = [
  [
    "Sunny",
    "Mumbai",
    ["Web development", "Mobile development"],
    ["JavaScript", "React", "Node.js"],
    1,
    "$100-$500",
    "sunny.tech",
  ],
  [
    "Riya",
    "Mumbai",
    ["Content Writing", "Copywriting"],
    ["SEO", "Blog Writing", "Editing"],
    2,
    "$50-$200",
    "riya-writes.com",
  ],
  [
    "Karan",
    "Bangalore",
    ["UI/UX Design", "Web Design"],
    ["Figma", "Adobe XD", "React"],
    3,
    "$200-$700",
    "karandesigns.io",
  ],
  [
    "Tanya",
    "Delhi",
    ["Digital Marketing", "Content Writing"],
    ["SEO", "Google Ads", "Instagram"],
    2,
    "$150-$400",
    "tanyamarkets.me",
  ],
  [
    "Aarav",
    "Chennai",
    ["AI Chatbot Dev", "Web Development"],
    ["JavaScript", "LangChain", "FastAPI"],
    1,
    "$300-$800",
    "botbyaarav.dev",
  ],
  [
    "Neha",
    "Pune",
    ["Illustration", "Sketching"],
    ["Procreate", "Photoshop", "Watercolor"],
    4,
    "$100-$300",
    "neha-art.in",
  ],
  [
    "Rahul",
    "Bangalore",
    ["Mobile App Dev", "Full Stack"],
    ["Flutter", "Firebase", "JavaScript"],
    2,
    "$250-$600",
    "rahulapps.xyz",
  ],
  [
    "Megha",
    "Pune",
    ["YouTube Thumbnail Design", "Content Creation"],
    ["Canva", "Photoshop", "Instagram"],
    1,
    "$40-$150",
    "meghacreates.net",
  ],
  [
    "Dev",
    "Chennai",
    ["Data Analysis", "Web Development"],
    ["SQL", "JavaScript", "Power BI"],
    3,
    "$200-$500",
    "devdatahub.io",
  ],
  [
    "Simran",
    "Delhi",
    ["Voice Over", "Script Reading"],
    ["English", "Hindi", "Editing"],
    1,
    "$30-$100",
    "simranspeaks.com",
  ],
  [
    "Yash",
    "Indore",
    ["Game Dev", "3D Modelling"],
    ["Unity", "C#", "Blender"],
    2,
    "$300-$1000",
    "yashgames.dev",
  ],
  [
    "Pooja",
    "Surat",
    ["Logo Design", "Branding"],
    ["Illustrator", "Photoshop", "Typography"],
    2,
    "$100-$400",
    "poojalogo.art",
  ],
  [
    "Zoya",
    "Mumbai",
    ["Virtual Assistant", "Admin Tasks"],
    ["Notion", "Slack", "Google Workspace"],
    1,
    "$50-$250",
    "zoyahustles.me",
  ],
  [
    "Ishaan",
    "Delhi",
    ["E-commerce", "Shopify Dev"],
    ["Shopify", "Liquid", "JavaScript"],
    3,
    "$150-$500",
    "ishaanstore.dev",
  ],
  [
    "Anjali",
    "Chennai",
    ["Technical Writing", "API Docs"],
    ["Markdown", "Postman", "JavaScript"],
    2,
    "$100-$300",
    "anjaliwrites.dev",
  ],
];
